platform :ios,	'7.0'

pod 'Masonry', '~> 0.6.4'
pod 'CYLTabBarController'
pod 'AFNetworking', '~> 3.0.4'
pod 'MJRefresh', '~> 3.1.0’
pod 'MJExtension', '~> 3.0.10'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~> 3.7.3'
