platform :ios,	'8.0'

pod 'Masonry', '~> 1.0.0'
pod 'AFNetworking', '~> 3.1.0’
pod 'MJRefresh', '~> 3.1.0’
pod 'MJExtension', '~> 3.0.10'
pod 'MBProgressHUD', '~> 0.9.2’
pod 'SDWebImage', '~> 3.7.5’

#类似新浪微博客户端中间的加号实现框架，需要时打开
#pod 'CYLTabBarController'