platform :ios,	'7.0'

pod 'Masonry', '~> 0.6.4'
pod 'AFNetworking', '~> 3.0.4'
pod 'MJRefresh', '~> 3.1.0’
pod 'MJExtension', '~> 3.0.10'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~> 3.7.3'

#类似新浪微博客户端中间的加号实现框架，需要时打开
#pod 'CYLTabBarController'